### PR TITLE
fix: Persist credentials (#411)

### PR DESCRIPTION
**Pull request by reneleonhardt**
Persist credentials, not only settings state:
* Credentials in form are filled/reset from password store
* Credentials are persisted to store on settings apply/ok (actual fix)
* Streamlined credentials to be null if user entered blank (whitespace)
* Credentials form and persistence is tested

Gotchas:
* YouSettingsForm persists to store directly, I suggest to move that to `GeneralSettingsConfigurable` like all other services do (user clicks Apply/OK)

### CODE REVIEW

**Comment by carlrobertoh** [comment]
> - Credentials added to settings state

This poses a security risk because the sensitive data will now be stored in plain text alongside other configuration files.

**Comment by reneleonhardt** [comment]
> This poses a security risk because the sensitive data will now be stored in plain text alongside other configuration files.

Now I found the culprit, the password store was only used for loading credentials, but not actually storing them 😅
I would still suggest to streamline You password handling with all other services.

**Comment by reneleonhardt** [comment]
I moved You password persistence from Sign In to Apply like all others, and fixed modelChanged detection.
Did you enable auto-squashing in this repo, or should I squash manually?

**Comment by carlrobertoh** [comment]
Yeah, originally, I loaded the credentials lazily whenever they were required. However, the issue arises because the `GeneralSettings` configuration form is bound to all the services. Thus, whenever there is a change in one of the services, all fields, including the credentials, need to be re-validated, and this causes an error/warning because the process runs on the EDT.

However, loading all credentials at once introduces another problem, because you must grant access to each of these credentials as soon as you start the IDE.

**Comment by carlrobertoh** [comment]
The UI is the bottleneck. All these services/providers need to have their own configuration form and must implement the `com.intellij.openapi.options.Configurable` interface.

So, essentially, we need to revert back to the original lazily loaded logic and change the way how the services are configured.

Screenshot 2024-04-15 at 13 31 46

**Pull request closed without merging**
