### PR TITLE
chore: Improve code

### PR DESCRIPTION
**Pull request by reneleonhardt**

### CODE REVIEW

**Comment by reneleonhardt** [comment]
@carlrobertoh I fixed mostly warnings, but also security vulnerabilities and minor problems with streams.

**Comment by carlrobertoh** [comment]
Nice, thank you! 👍 

In the future, I would like to start migrating from Java to Kotlin. Or at least, I would like to see all the new CodeGPT components written in Kotlin. Besides the language-specific advantages over Java itself, the new components/services in the JetBrains API are also written in Kotlin first and foremost.

**Comment by reneleonhardt** [comment]
Sure, good idea, can you point me to a good overview how to debug a plugin locally? 😅
Then it would be much easier trying to reproduce problems caused by user input in the UI 😉

**Comment by carlrobertoh** [comment]
I'm not really aware of any good documentation. I usually run the Gradle task (`./gradlew runIde`) in debug mode in my IDE. The tasks are automatically recognized by the Gradle plugin, which should come by default for IntelliJ. 

Screenshot 2024-04-10 at 22 27 37

**Pull request merged**
