### PR TITLE
Editable system role 

### PR DESCRIPTION
**Pull request by FxProjects**
image
image
image
I added the ability to change the parameter for the system role. which allows you to more accurately and conveniently configure the bot and specify its behavioral data

### CODE REVIEW

**Comment by FxProjects** [comment]
image
image
image
And add abiluty to define by user custom hotkeys for actions 
image

**Comment by carlrobertoh** [comment]
Thank you for contributing!

First of all, I'd love if these two distinct features have a separate pull requests.

Secondly, the system role messages aren't really part of the toolwindow's logic i.e. it should be configurable while overriding the API request params (which in fact doesn't exist today). Request param overriding should be done inside the plugin's settings, similarly how selected code actions are configured. Also, there is an [open ticket](https://github.com/carlrobertoh/CodeGPT/issues/72) for that.

Thirdly, the key mappings should also include actions such as submitting the input, copying/replacing the generated code, navigating between main tabs(Chat/Conversation History), selecting the previous conversation etc. However, I'm also happy to accept the partial logic for it.

Lastly, try to keep the code changes as minimal as possible (e.g. don't commit the file if it only includes the code formatting). Also, I'm trying to follow the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) since the plugin doesn't specify any code style rules.

**Comment by FxProjects** [comment]
To be honest, I don’t write in java at all, but I’ll definitely read and improve my skills for the future and try to comply with these standards.
I understand that here you can really make a huge functionality and it will take a lot of time and I have no right to demand these functions from you, so I tried to do it myself as it turned out and shared who might need it as developments.

**Comment by carlrobertoh** [comment]
That's perfectly fine! 🙂 

For example, I'm happy to accept the logic for the actions key mappings if you tidy up the code a bit and lose the other functionality(or create another PR for it).

**Comment by jmckenzie-dev** [comment]
`I'm happy to accept the logic for the actions key mappings`
Just want to chime in and say: this would make me a _very happy ideaVim user_. 😀 

Appreciate the plugin and appreciate the work on adding these key mappings. Super impressed with all of it!

**Comment by carlrobertoh** [comment]
@jmckenzie-dev I will try to add the basic key mappings next week.

**Comment by carlrobertoh** [comment]
@jmckenzie-dev Key mappings are now available in version 1.10.7 (pending Jetbrains approval).

**Comment by jmckenzie-dev** [comment]
🎉 

That's freaking awesome. Thanks!

**Pull request closed without merging**
