### PR TITLE
Draft: feat: Support Llama 3 model (#478)

### PR DESCRIPTION
**Pull request by reneleonhardt**
Wow, fresh of the press, seems to be one of the best models now!! 🚀

Waiting for llama.cpp support... 😅
https://github.com/ggerganov/llama.cpp/issues/6747
https://github.com/ggerganov/llama.cpp/pull/6751

### CODE REVIEW

**Comment by carlrobertoh** [comment]
Is there any more work to be expected here, or can we perhaps remove the "Draft" prefix?

**Comment by reneleonhardt** [comment]
As far as I can see it's finished (can you double-check the InfillPrompt?), I'm just waiting for the llama.cpp server support 😅
Or can you check it locally? In LM Studio I did see no big problems, the model is amazing, I just have to ask it to tell the truth when it fantasized to me about non-existing Kotlin operators 😉
7B Q8 is super fast on M1 Max 🚀

**Comment by carlrobertoh** [comment]
Nice! It looks like the model doesn't support infilling, or at least I couldn't find anything. Maybe we can just remove the new infill template for now.

**Comment by reneleonhardt** [comment]
> Nice! It looks like the model doesn't support infilling, or at least I couldn't find anything. Maybe we can just remove the new infill template for now.

Really? All main calls I saw contained --in-prefix and suffix https://github.com/ggerganov/llama.cpp/issues/6747#issuecomment-2065013606 that's why I added it 😅
But if you think it's a problem I can remove it for now 🙂

**Comment by carlrobertoh** [comment]
Hmm, their model card doesn't specify anything related to that matter - https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3

**Comment by reneleonhardt** [comment]
All I can see is that there is a lot of confusion about the model, some people have many problems, some have none... I guess it dependes how you use it.
phymbert mentioned a special `infill` endpoint https://github.com/ggerganov/llama.cpp/issues/6747#issuecomment-2065117938, is CodeGPT using that?

**Comment by carlrobertoh** [comment]
No, but we were using it for a while, I think. However, I can't remember the reason why we switched back.

**Pull request merged**
